name: "eks"
on:
  workflow_dispatch:

jobs:
  Plan:
    uses: rabbyrobin/app_task.github/ci/cd/workflow/eks.yml@Aws-Terraform-Lab
    with:
      gh_environment: test-dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TRF_API_TOKEN }}

  Apply:
    needs: Plan
    uses: rabbyrobin/app_task.github/ci/cd/workflow/eks.yml@Aws-Terraform-Lab
    with:
      gh_environment: test-dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TRF_API_TOKEN }}
