name: "01-EKS"
on:
  workflow_dispatch:

jobs:
  Plan:
    uses: rabbyrobin/app_task/TRFEKS-Lab/aws_tf_plan.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TRF_API_TOKEN }}

  Apply:
    needs: Plan
    uses: rabbyrobin/app_task/TRFEKS-Lab/aws_tf_plan.yml@main
    with:
      gh_environment: test-dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TRF_API_TOKEN }}
